name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # Run on version tags like v1.2.3
  workflow_dispatch:    # Allows for a manual trigger in case something goes wrong
    inputs:
      version:
        description: "Version to publish (e.g. 1.2.4)"
        required: true

jobs:
  test:
    name: Run Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run tests
        run: python -m unittest discover

  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to access tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: 'pip' # caching pip dependencies

      - name: Install build tools (from optional deps)
        run: |
          python -m pip install --upgrade pip
          pip install .[build]

      - name: Build package
        run: python -m build

      - name: Extract GitHub Release Notes
        id: release_notes
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          prerelease: false
          body: ${{ github.event.release.body }}

      - name: Upload release to PyPI
        runs-on: ubuntu-latest
        environment:
          name: pypi
          url: https://pypi.org/p/tn-sdk/
        permissions:
          id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
        steps:
        # retrieve your distributions here

        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
